Iter13
kvvPro/metric-collector pull request #13
Opened 2023-07-16 21:12 UTC by kvvPro

2023-07-17 14:06 UTC, valentinsoe requested changes
Спасибо за работу.
Повторяемые ошибки не совсем соответсвуют заданию.
Из важного - не должен агент и сервер вызывать panic, если может нормально обработать ошибку.
В случае агента panic - автоматически означает остановку отсылки метрик. Хотя проблема могла быть в том, что просто на полчаса отвалился интернет.
Для сервера точно также внутри обработчиков http паника это автоматический обрыв соединения с клиентом.

2023-07-17 14:06 UTC, valentinsoe commented on cmd/agent/client/client.go
> +			Sugar.Fatalw(err.Error())
Кажется даже если нам не удалось отправить данные за 3 попытки, это не повод прекращать работу агента.

2023-07-17 14:06 UTC, valentinsoe commented on cmd/agent/client/client.go
> +// func (cli *Client) updateMetricsJSON(allMetrics []metrics.Metric) error {
Просьба не оставлять такие комменты с "устаревшим" кодом

2023-07-17 14:06 UTC, valentinsoe commented on cmd/server/__debug_bin3554265855
лишний файл

2023-07-17 14:06 UTC, valentinsoe commented on cmd/server/app/app.go
> +	mem "github.com/kvvPro/metric-collector/internal/storage/memstorage"
Занудство. Кажется нет необходимости в алиасах для этих пакетов.

2023-07-17 14:06 UTC, valentinsoe commented on cmd/server/app/app.go
> +		storage:         st,
st при неправильно заданных параметрах может быть nil.
Кажется в таком случае лучше, чтобы сервер не запустился.

2023-07-17 14:06 UTC, valentinsoe commented on cmd/server/app/app.go
> +		panic(err)
Со стороны клиента это будет выглядеть как обрыв соединения. Это слишком "грубо"
В нормальной работе приложения не должны возникать panic, они уместны при инициализации приложения. Когда оно например из-за неправильной конфигурации не может запуститься.

2023-07-17 14:06 UTC, valentinsoe commented on cmd/server/app/handlers.go
> +	body := "OK!"
Если пишется что-то в тело ответа, то хорошим тоном было бы поставить заголовок content-type

2023-07-17 14:06 UTC, valentinsoe commented on cmd/server/app/handlers.go
> +	w.WriteHeader(http.StatusOK)
WriteHeader здесь уже вызывать поздно.
w.Write уже его вызвал(если это стандратный http.ResponseWriter)

2023-07-17 14:06 UTC, valentinsoe commented on cmd/server/app/handlers.go
> +	json.NewEncoder(bodyBuffer).Encode(updatedMetrics)
При такой логике работы, кажется json.Marshal(updatedMetrics) было бы короче

2023-07-17 14:06 UTC, valentinsoe commented on cmd/server/app/handlers.go
> +	json.NewEncoder(bodyBuffer).Encode(updatedMetrics)
Да и кажется это осталось от "отладки". Из итогового кода кажется это можно убрать.

2023-07-17 14:06 UTC, valentinsoe commented on internal/retry/retry.go
> +/*
Лучше подключить это как пакет, а не делать копию кода.
Это кстати может теоретически нарушать лицензионные соглашения.

2023-07-17 14:06 UTC, valentinsoe commented on internal/storage/postgres/postgres.go
> +func (s *Settings) Update(t string, n string, v string) error {
Если метод не реализован, лучше бы он возвращал ошибку.

2023-07-17 14:06 UTC, valentinsoe commented on internal/storage/postgres/postgres.go
> +func (s *Settings) GetValue(t string, n string) (any, error) {
Явно лишняя функция.

2023-07-17 18:41 UTC, kvvPro commented on cmd/agent/client/client.go
> +			Sugar.Fatalw(err.Error())
Убрал панику

2023-07-17 18:42 UTC, kvvPro commented on cmd/agent/client/client.go
> +// func (cli *Client) updateMetricsJSON(allMetrics []metrics.Metric) error {
удалил

2023-07-17 18:42 UTC, kvvPro commented on cmd/server/__debug_bin3554265855
удалил

2023-07-17 18:43 UTC, kvvPro commented on cmd/server/app/app.go
> +	mem "github.com/kvvPro/metric-collector/internal/storage/memstorage"
убрал

2023-07-17 18:46 UTC, kvvPro commented on cmd/server/app/app.go
> +		storage:         st,
вроде как это условие недопустит nil в st. Либо будет БД (и только в случае успешного подключения), либо memstorage - который всегда создастся
<img width="664" alt="image" src="https://github.com/kvvPro/metric-collector/assets/7610059/c2a8c447-169a-4383-b74c-ee8e618edbc5">

2023-07-17 18:48 UTC, kvvPro commented on cmd/server/app/app.go
> +		storage:         st,
Добавил доп проверку на nil для st

2023-07-17 18:50 UTC, kvvPro commented on cmd/server/app/handlers.go
> +	body := "OK!"
добавил

2023-07-17 18:52 UTC, kvvPro commented on cmd/server/app/handlers.go
> +	w.WriteHeader(http.StatusOK)
В примерах в уроках он был всегда последним, поэтому и оставлял так. 
Переместил до записи тела

2023-07-17 18:54 UTC, kvvPro commented on cmd/server/app/handlers.go
> +	json.NewEncoder(bodyBuffer).Encode(updatedMetrics)
Сначала добавлял, потому что при ответе возвращал тело ответа с метриками, но так как тесты не ждали тела ответа, то убрал. А это осталось.
Если тесты правиться не будут, тогда уберу

2023-07-17 18:56 UTC, kvvPro commented on internal/retry/retry.go
> +/*
С этой [библиотекой](https://github.com/avast/retry-go/tree/v4.3.4) был затык. Никак не хотела импортироваться именно версия 4.3.4 (она же последняя), импортировалась только 3.0.0. Поэтому и перенес ее код локально.

2023-07-17 18:57 UTC, kvvPro commented on internal/storage/postgres/postgres.go
> +func (s *Settings) Update(t string, n string, v string) error {
По заданию не совсем понятно, нужно ли для хранилища с типом БД делать эти функции (тесты и так проходят)

2023-07-17 18:58 UTC, kvvPro commented on internal/storage/postgres/postgres.go
> +func (s *Settings) GetValue(t string, n string) (any, error) {
Не лишняя. Если удалить, тогда Settings не будет имплементировать интерфейс Storage

2023-07-18 08:47 UTC, kvvPro commented on cmd/server/app/app.go
> +		panic(err)
Добавил попытки. Остальные паники убрал (заменил на попытки, либо возврат непосредственных ошибок выше по стеку)

2023-07-20 07:03 UTC, valentinsoe commented on internal/storage/postgres/postgres.go
> +func (s *Settings) Update(t string, n string, v string) error {
Реализовывать нужно. Но если ты ожидаешь, что он не будет вызываться, лучше вернуть ошибку.
Если вдруг кто-то когда-то его вызовет - "ошибка" не будет скрыта.

2023-07-20 07:05 UTC, valentinsoe commented on internal/storage/postgres/postgres.go
> +func (s *Settings) GetValue(t string, n string) (any, error) {
Тогда  стоит написать полную реализацию.
А заодно переименовать тип. Потому что тип Settings имеет функционал хранилища(метрик). А не настроек:)

2023-07-20 07:08 UTC, valentinsoe commented on cmd/server/app/app.go
> +		storage:         st,
Да, мой косяй. Пропутсил момент с return в случае DB

2023-07-20 07:30 UTC, valentinsoe commented on cmd/server/app/app.go
> +				return srv.storage.UpdateBatch(context.Background(), m)
Логика повторов несколько странная. Первый раз мы проверим что ошибка у нас связана с соединением.
Последующие 3 попытки мы будем пробовать независимо от типа ошибки.

2023-07-20 07:32 UTC, valentinsoe requested changes
Спасибо за исправления.
Но повтор ошибок все еще 
1) не соответсвует заданию(1,3,5 секунд)
2) не совсем корректно устроен

2023-07-20 22:08 UTC, kvvPro commented on cmd/server/app/app.go
> +				return srv.storage.UpdateBatch(context.Background(), m)
Упростил вызов.
Сделал, чтобы сразу передавать retriable функцию в библиотеку.
Добавил проверку на тип ошибки перед каждой попыткой.
Шаг увеличения и до этого был в начальной инициализации библиотеки - добавил еще явно передаваемые параметры

2023-07-25 17:46 UTC, valentinsoe approved these changes
Спасибо за исправления!

2023-07-25 17:50 UTC, merged