Iter15
kvvPro/metric-collector pull request #15
Opened 2023-07-25 09:30 UTC by kvvPro

2023-08-01 07:01 UTC, valentinsoe commented on cmd/agent/client/client.go
> +		newCPU := metrics.NewCommonMetric("CPUutilization1", metrics.MetricTypeGauge, nil, &cpu)
В задании не очень явно указано, но ожидается сбор метрики по каждому ядру. 
1 в конце в названии метрики - номер ядра.

2023-08-01 07:15 UTC, valentinsoe requested changes
Для начала,  извиняюсь за долгое время проверки.

Спасибо за работу. 
Написал 2 замечания. Одно про количество метрик - согласен, там далеко не самое очевидное задание.
Второе про небуфферизованный канал. Сбор метрик будет всегда блокироваться, пока нет ожидающего воркера. Например если запустить 1 воркер, то сбор метрик будет происходить реже, чем отправка.

2023-08-01 07:15 UTC, valentinsoe commented on cmd/agent/client/client.go
> +		queue:          make(chan []metrics.Metric),
Канал сделан не буфферизованным. А значит сбор метрик каждый раз будет ждать отправки метрик.

2023-08-02 07:04 UTC, kvvPro commented on cmd/agent/client/client.go
> +		queue:          make(chan []metrics.Metric),
Просьба смотреть этот PR - https://github.com/kvvPro/metric-collector/pull/14

2023-08-02 07:04 UTC, kvvPro commented on cmd/agent/client/client.go
> +		queue:          make(chan []metrics.Metric),
Просьба смотреть этот PR - https://github.com/kvvPro/metric-collector/pull/14

2023-08-04 06:20 UTC, valentinsoe commented on cmd/agent/client/client.go
> +		queue:          make(chan []metrics.Metric),
Тот PR относится к 14 итерации. Она не сдается на проверку.

2023-08-04 06:25 UTC, kvvPro commented on cmd/agent/client/client.go
> +		queue:          make(chan []metrics.Metric),
> Тот PR относится к 14 итерации. Она не сдается на проверку.

на момент отправки, ветка 15 инкремента не запускала тесты - о чем я писал в общем чате. Поэтому и отправлял в 14 ветке. Собственно какая разница? тестов для 15 инкремента все равно нет.

2023-08-04 07:54 UTC, kvvPro commented on cmd/agent/client/client.go
> +		queue:          make(chan []metrics.Metric),
Собственно о чем и говорил - все тесты скипаются при коммите в 15 бранч
<img width="1083" alt="image" src="https://github.com/kvvPro/metric-collector/assets/7610059/fc2f2724-af8b-474d-8813-45606fa76f42">

2023-08-04 08:46 UTC, valentinsoe commented on cmd/agent/client/client.go
> +		queue:          make(chan []metrics.Metric),
Надо обновить шаблон репозитория:
https://github.com/kvvPro/metric-collector#%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD%D0%B0

2023-08-04 08:48 UTC, valentinsoe approved these changes
Спасибо за исправления!

2023-08-08 20:30 UTC, merged