Iter9
kvvPro/metric-collector pull request #9
Opened 2023-07-04 09:24 UTC by kvvPro

2023-07-07 15:21 UTC, valentinsoe commented on cmd/agent/client/client.go
> +	"github.com/kvvPro/metric-collector/internal/metrics"
Настрой пожалуйста в IDE пакет goimports, он чуть лучше сортирует импорты

2023-07-07 16:00 UTC, valentinsoe requested changes
Спасибо за работу.
Из критичных замечаний - отправка счетчика со стороны агента имеет баг, некорректная логика сжатия ответа сервера(опирается на заголовки клиента).
Глобально кажется что много всего усложнено, там где можно обойтись простым решением.
Нет необходимости писать массовые операции. В целом логика того, что по одному адресу могут приниматься два разных формата сообщения - не очень удачная. Для массового запроса/обновления лучше сделать отдельный адрес и обработчик.

2023-07-07 16:00 UTC, valentinsoe commented on cmd/agent/client/client.go
> +type IMetric interface {
В соглашении об именовании go интерфейсы называются в соответствии с тем, что они умеют делать(Reader, Writer и т.д.)
Добавлять I выбивается сильно из соглашения об именовании.

2023-07-07 16:00 UTC, valentinsoe commented on cmd/agent/client/client.go
> +			"status", response.Status, // получаем перехваченный код статуса ответа
Он не перехваченный, а полученный:)

2023-07-07 16:00 UTC, valentinsoe commented on cmd/agent/client/client.go
> +		Sugar.Infoln("Request body was read")
Response body?

2023-07-07 16:00 UTC, valentinsoe commented on cmd/agent/client/client.go
> +		Sugar.Infoln("client-response: ", string(dataResponse[:]))
server-response?

2023-07-07 16:00 UTC, valentinsoe commented on cmd/agent/client/client.go
> +		Sugar.Infoln("client-response: ", string(dataResponse[:]))
dataResponse[:] - то же самое, что dataResponse, предлагаю не писаь лишнее

2023-07-07 16:00 UTC, valentinsoe commented on cmd/agent/client/client.go
> +		_, serr := io.Copy(io.Discard, response.Body)
Выше уже прочитан response.body, зачем его повторно читать? К тому же зачем вызывать панику и прерывать работу агента, если это не получилось?

2023-07-07 16:00 UTC, valentinsoe commented on cmd/agent/client/client.go
> +	// bodyBuffer := new(bytes.Buffer)
Рекомендую не оставлять такие большие куски комментариев в коде.

2023-07-07 16:00 UTC, valentinsoe commented on cmd/agent/client/client.go
> +	request.Header.Set("Content-Encoding", "gzip")
Сжатие в gzip закомментировано. А заголовок выставляется.

2023-07-07 16:00 UTC, valentinsoe commented on cmd/agent/client/client.go
>  func (cli *Client) PushMetrics() {
Работа со счетчиком сделана некорректно.
Счетчик на сервере будет расти быстрее чем нужно.
Если мы читаем его раз 2 секунды, а отправляем раз в 10, то будет следующее:
Через 10 секунд мы отправим на сервер 5, через 20 секунд мы отправим на сервер 10. Он добавит это значение к текущему и получит 15, и так далее.

2023-07-07 16:00 UTC, valentinsoe commented on cmd/agent/client/client.go
>  	request.Header.Set("Content-Type", cli.contentType)
Предлагаю либо использовать cli.contentType в новом методе, либо удалить его отовсюду.
Мне больше нравится второй вариант.

2023-07-07 16:00 UTC, valentinsoe commented on cmd/server/app/app.go
> +	st "github.com/kvvPro/metric-collector/internal/storage"
Не вижу необходимости использовать alias для пакета.

2023-07-07 16:00 UTC, valentinsoe commented on cmd/server/app/app.go
> +			Sugar.Infoln("Save to file failed: ", err.Error())
Если не удалось сохранить данные в файл, кажется игнорировать такую ошибку не стоит.

2023-07-07 16:00 UTC, valentinsoe commented on cmd/server/app/app.go
> +func (srv *Server) GetRequestedValues(m []metrics.Metric) []metrics.Metric {
У нас в задании не было массовых операций.

2023-07-07 16:00 UTC, valentinsoe commented on cmd/server/app/app.go
> +			Sugar.Infoln("Read values failed: ", err.Error())
Такую ошибку тоже не стоит игнорировать.

2023-07-07 16:00 UTC, valentinsoe commented on cmd/server/app/files.go
> +	reader := io.NopCloser(bytes.NewReader(data))
NewDecoder не требует ReadCloser, зачем мы его создаем?

2023-07-07 16:00 UTC, valentinsoe commented on cmd/server/app/handlers.go
> +		enableCompress := strings.Contains(ContentTypesForCompress, r.Header.Get("Content-Type"))
Мы должны сжимать ответ, если Content-Type ответа, а не запроса попадает в список.

2023-07-07 16:00 UTC, valentinsoe commented on cmd/server/app/handlers.go
> +		sendsGzip := strings.Contains(contentEncoding, "gzip")
Content-Encoding должен быть строго равен gzip

2023-07-07 16:00 UTC, valentinsoe commented on cmd/server/app/handlers.go
> +	updatedMetrics := srv.GetRequestedValues(requestedMetrics)
updatedMetrics - не соответсвует действительности. Мы же не обновляем их в этом методе, а запрашиваем.

2023-07-07 16:00 UTC, valentinsoe commented on cmd/server/config/flags.go
> +	hp := strings.Split(s, ":")
Не сторонник подобной логики. Мы разделяем адрес на хост и порт.
При этом не проверяем их форматы, а потом склеиваем в строку обратно:)

К тому же данная логика не позволит работать с host заданным в виде ipv6 адреса.

2023-07-07 16:00 UTC, valentinsoe commented on cmd/server/config/flags.go
> +	if _, isSet := os.LookupEnv("STORE_INTERVAL"); !isSet {
Можно просто сначала прочитать флаги, а потом "поверх" переменные окружения. Код будет чуть проще.

2023-07-07 17:14 UTC, kvvPro commented on cmd/agent/client/client.go
>  func (cli *Client) PushMetrics() {
по заданию так и есть - при каждом чтении увеличиваем его и затем отправляем.  
<img width="764" alt="image" src="https://github.com/kvvPro/metric-collector/assets/7610059/a24806ab-71cf-4031-b110-e4643e2de8ba">

2023-07-07 17:19 UTC, kvvPro commented on cmd/server/app/app.go
> +			Sugar.Infoln("Save to file failed: ", err.Error())
Об этом в задании не сказано =) зависит в принципе от критичности операции - если это сайд-функция, то можно и игнорить. Исправлю)

2023-07-07 18:09 UTC, kvvPro commented on cmd/agent/client/client.go
>  func (cli *Client) PushMetrics() {
Считаю, что логика реализована верно

2023-07-07 18:30 UTC, kvvPro commented on cmd/server/config/flags.go
> +	if _, isSet := os.LookupEnv("STORE_INTERVAL"); !isSet {
тогда нарушим условие. Сначала проверяем переменные окружения и только если они не заданы - читаем флаги. Если переписать, как вы говорите - то мы "затрем" флагами сначала
<img width="750" alt="image" src="https://github.com/kvvPro/metric-collector/assets/7610059/92bac91e-8ae7-46e6-97e9-caa9d4c067fd">

2023-07-08 13:18 UTC, kvvPro commented on cmd/server/config/flags.go
> +	hp := strings.Split(s, ":")
Убрал

2023-07-08 13:18 UTC, kvvPro commented on cmd/server/app/handlers.go
> +		sendsGzip := strings.Contains(contentEncoding, "gzip")
Добавил

2023-07-08 13:19 UTC, kvvPro commented on cmd/server/app/files.go
> +	reader := io.NopCloser(bytes.NewReader(data))
Убрал

2023-07-08 13:20 UTC, kvvPro commented on cmd/server/app/app.go
> +			Sugar.Infoln("Read values failed: ", err.Error())
Тесты некорректно на это реагируют - если прокидываем ошибку, то тесты ожидают, что сервер запустится с тем, что не смогу прочитать данные из файла

2023-07-08 13:20 UTC, kvvPro commented on cmd/server/app/app.go
> +	st "github.com/kvvPro/metric-collector/internal/storage"
убрал

2023-07-08 13:20 UTC, kvvPro commented on cmd/agent/client/client.go
>  	request.Header.Set("Content-Type", cli.contentType)
убрал

2023-07-08 13:21 UTC, kvvPro commented on cmd/agent/client/client.go
>  func (cli *Client) PushMetrics() {
> Работа со счетчиком сделана некорректно. Счетчик на сервере будет расти быстрее чем нужно. Если мы читаем его раз 2 секунды, а отправляем раз в 10, то будет следующее: Через 10 секунд мы отправим на сервер 5, через 20 секунд мы отправим на сервер 10. Он добавит это значение к текущему и получит 15, и так далее.

Скорректировал

2023-07-08 13:21 UTC, kvvPro commented on cmd/agent/client/client.go
> +	request.Header.Set("Content-Encoding", "gzip")
добавил сжатие

2023-07-08 13:21 UTC, kvvPro commented on cmd/agent/client/client.go
> +	// bodyBuffer := new(bytes.Buffer)
убрал

2023-07-08 13:21 UTC, kvvPro commented on cmd/agent/client/client.go
> +		_, serr := io.Copy(io.Discard, response.Body)
убрал

2023-07-08 13:21 UTC, kvvPro commented on cmd/agent/client/client.go
> +		Sugar.Infoln("client-response: ", string(dataResponse[:]))
убрал

2023-07-08 13:22 UTC, kvvPro commented on cmd/agent/client/client.go
> +		Sugar.Infoln("Request body was read")
скорректировал

2023-07-08 13:22 UTC, kvvPro commented on cmd/agent/client/client.go
> +			"status", response.Status, // получаем перехваченный код статуса ответа
скорректировал

2023-07-08 13:22 UTC, kvvPro commented on cmd/agent/client/client.go
> +type IMetric interface {
скорректировал

2023-07-08 15:52 UTC, kvvPro commented on cmd/server/app/handlers.go
> +		enableCompress := strings.Contains(ContentTypesForCompress, r.Header.Get("Content-Type"))
скорректировано

2023-07-11 19:59 UTC, valentinsoe commented on cmd/agent/client/client.go
> +	request.Header.Set("Content-Encoding", "gzip")
Это старый метод. Который перестал выставлять тип контента, но стал устанавливать заголовок сжатия.
Он не используется, но написан сейчас не корректно.
Тип контента должен остаться. А вот сжатия в коде нет(как и тела запроса)

2023-07-11 20:01 UTC, valentinsoe commented on cmd/server/app/app.go
> +			Sugar.Infoln("Read values failed: ", err.Error())
Да, извиняюсь. Тут действительно мое мнение расходится с тестами.

2023-07-11 20:04 UTC, valentinsoe commented on cmd/server/config/flags.go
> +	if _, isSet := os.LookupEnv("STORE_INTERVAL"); !isSet {
Мы сначала затрем флагами. А потом если установлены переменные окружения, то затрем еще и ими.
И как раз достигнем нужного результата.

2023-07-11 20:04 UTC, valentinsoe approved these changes
Спасибо за исправления.

Не все мелкие замечания исправлены, но это не критично для принятия работы.

2023-07-12 09:44 UTC, merged